*** Variables ***
${AddressBook_Title}    Update Your Address Book

${AddressBook_fname}     //*[@id="ae-form-adbk-firstname"]
${AddressBook_lname}     //*[@id="ae-form-adbk-lastname"]
${AddressBook_addr1}     //*[@id="ae-form-adbk-address"]
${AddressBook_addr2}     //*[@id="ae-form-adbk-suburb"]
${AddressBook_postal}    //*[@id="ae-form-adbk-postal"]
${AddressBook_city}      //*[@id="ae-form-adbk-city"]
${AddressBook_prov}      //*[@id="ae-form-adbk-prov-drpdn"]
${AddressBook_country}   //*[@id="ae-form-adbk-country"]
${AddressBook_save}      //*[@id="btn-createacct"]
${AddressBook_save_message}    Your account has been successfully updated
${AddressBook_save_ok}    //*[@id="cboxClose"]

${fname}    Test 1
${lname}    CC 1
${addr1}    75 West Wilmot St. 1
${addr2}    Richmond Hill 1
${postal}    L4B1K8
${city}    Richmond Hill 1
${prov}    MB
${country}    Canada


${og_fname}    Test
${og_lname}    CC
${og_addr1}    75 West Wilmot St.
${og_addr2}    Richmond Hill
${og_postal}    L4B1K7
${og_city}    Richmond Hill
${og_prov}    ON

