*** Variables ***

#Checkout
${CCWEB_Cart_ProceedCheckout}                 //*[@id="cart"]/div[2]/div[2]/div/button
${CCWEB_Checkout_PickupRadio}                 //*[@id="ch-shipto-store"]
${CCWEB_Checkout_ProceedToPayment}            //*[@id="ch-form"]/div[2]/div/button[2]
${CCWEB_Checkout_ProceedToReview}             //*[@id="checkout_payment"]
${CCWEB_Checkout_PlaceOrder}                  //*[@id="check-out"]/div[2]/form/div[3]/div/button[2]