*** Variables ***

${Wishlist_Image}           //*[@id="wishlist-form"]/section[1]/div[1]/div/img
${Wishlist_ItemCode}        VCSAP00081
${Wishlist_ItemDesc}        //*[@id="wishlist-form"]/section[1]/div[2]/div/div[1]/p[2]/a
${Wishlist_Price}           $

${Wishlist_Select_1}        //*[@id="wishlist-form"]/section[1]/div[2]/div/div[3]/div/label
# ${Wishlist_Select_1}        //*[@id="subcat212526"]
${Wishlist_Delete}          //*[@id="wishlist-form"]/section[2]/div/button
