*** Variables ***

#Order Record
${OrderHistory_OrderNumber}        2668971
${OrderHistory_OrderDate}          January 28, 2022
${OrderHistory_Product}            1
${OrderHistory_Cost}               $14.94
${OrderHistory_Status}             Cancel Confirmed

${OrderHistory_ViewDetails}        .//button/span[text()='View Details']

# //button[contains(text(),'View Details')]
# (text(),'${Selected_Category}')

# //a[contains(text(),'${Selected_Category}')]