*** Variables ***

#Locators
${CCWEB_SiteHeader}    //*[@id="header-top"]
${CCWEB_HeaderBar}     //*[@id="header-search"]
${CCWEB_HeaderNav}     //*[@id="header-shop"]
${CCWEB_Carousel}      //div[@class="main-carousel hero-banner flickity-enabled is-draggable"]
${CCWEB_HomePage}      //div[@class="home-page"]
${CCWEB_Subscriptions}    //*[@id="subscriptions"]
${CCWEB_Footer}        //div[@class="d-block order-1 order-sm-2 bg-cc pt-0"]