*** Variables ***
${ShoppingCart_AddQty}        //*[@id="shopping_cart"]/div[2]/div/div[2]/div/div[2]/p/a[2]
${ShoppingCart_SubtractQty}   //*[@id="shopping_cart"]/div[2]/div/div[2]/div/div[2]/p/a[1]
${ShoppingCart_Quantity}      //*[@id="shopping_cart"]/div[2]/div/div[2]/div/div[2]/p/input
${ShoppingCart_Delete}        //*[@id="shopping_cart"]/div[2]/div/div[2]/div/div[2]/p/i

# ${item1}    CAICA00696